networks:
  mf:
    driver: bridge

services:
  postgresql:
    image: postgresql
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
    container_name: mf-postgresql
    command: postgres
    networks:
      - mf

  backend:
    depends_on:
      - alembic
      - redis
    build:
      context: .
      dockerfile: docker/backend/app/Dockerfile
    command: "uvicorn mindfus.backend:app --host 0.0.0.0 --port 8000"
    container_name: mf-backend
    networks:
      - mf
    ports:
      - "8000:8000"

  alembic:
    depends_on:
      - postgresql
    build:
      context: .
      dockerfile: docker/backend/app/Dockerfile
    command: "alembic upgrade head"
    container_name: mf-alembic
    networks:
      - mf

  frontend:
    depends_on:
      - backend
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    container_name: mf-frontend
    networks:
      - mf
    ports:
      - "8080:8080"

  redis:
    image: redis/redis-stack-server:latest
    container_name: mf-redis
    ports:
      - "6379:6379"
    networks:
      - mf

  celery:
    depends_on:
      - redis
    build:
      context: .
      dockerfile: docker/backend/app/Dockerfile
    command: "celery -A mindfus.celery.celery_app worker"
    container_name: mf-celery
    networks:
      - mf